Repository AY2021S1-CS2103T-F13-2/tp, pull requests merged in 2020-10, with the labels that each got.

#84 Refactor addcommand
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/bookmark/MainApp.java
  src/main/java/seedu/bookmark/logic/commands/AddCommand.java
  src/main/java/seedu/bookmark/logic/parser/AddCommandParser.java
  src/main/java/seedu/bookmark/logic/parser/ParserUtil.java
  src/main/java/seedu/bookmark/model/book/Bookmark.java
  src/main/java/seedu/bookmark/storage/JsonAdaptedBook.java
  src/test/java/seedu/bookmark/logic/LogicManagerTest.java
  src/test/java/seedu/bookmark/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/bookmark/logic/commands/AddCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/bookmark/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/bookmark/logic/parser/CommandParserTest.java
  src/test/java/seedu/bookmark/model/book/BookTest.java
  src/test/java/seedu/bookmark/model/book/BookmarkTest.java
  src/test/java/seedu/bookmark/model/book/GenreTest.java
  src/test/java/seedu/bookmark/model/book/UniqueLibraryTest.java
  src/test/java/seedu/bookmark/testutil/BookBuilder.java
  src/test/java/seedu/bookmark/testutil/BookUtil.java
  src/test/java/seedu/bookmark/testutil/TypicalBooks.java
Labels: type.Story

#83 Updating devguide
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.Documentation

#87 Fix leading zeroes problem and refactor ListCommand
  src/main/java/seedu/bookmark/commons/core/LogsCenter.java
  src/main/java/seedu/bookmark/commons/util/StringUtil.java
  src/main/java/seedu/bookmark/logic/commands/ListCommand.java
  src/main/java/seedu/bookmark/logic/parser/ParserUtil.java
Labels: type.Bug, type.Story

#94 Edit helpcommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/bookmark/ui/HelpBox.java
  src/main/java/seedu/bookmark/ui/HelpWindow.java
  src/main/resources/images/add_command.png
  src/main/resources/images/delete_command.png
  src/main/resources/images/edit_command.png
  src/main/resources/images/list_command.png
  src/main/resources/images/view_command.png
  src/main/resources/view/HelpBox.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story

#103 Update DG for Ui and enable assertions
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiViewClassDiagram.puml
  docs/diagrams/ViewSwitchingActivityDiagram.puml
  docs/diagrams/ViewSwitchingSequenceDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiViewClassDiagram.png
  docs/images/ViewSwitchingActivityDiagram.png
  docs/images/ViewSwitchingSequenceDiagram.png
Labels: type.Documentation

#106 Edit UML diagram in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/bookmark/model/ModelManager.java
Labels: type.Documentation

#110 Add FindCommand in Developer's Guide
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindState1.puml
  docs/diagrams/FindState2.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/FindState1.png
  docs/images/FindState2.png
Labels: type.Documentation

#97 Notes foundation
  docs/UserGuide.md
  src/main/java/seedu/bookmark/logic/commands/AddNoteCommand.java
  src/main/java/seedu/bookmark/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/bookmark/logic/parser/CliSyntax.java
  src/main/java/seedu/bookmark/logic/parser/CommandParser.java
  src/main/java/seedu/bookmark/logic/parser/ParserUtil.java
  src/main/java/seedu/bookmark/model/book/Book.java
  src/main/java/seedu/bookmark/model/book/Note.java
  src/main/java/seedu/bookmark/model/util/SampleDataUtil.java
  src/main/java/seedu/bookmark/storage/JsonAdaptedBook.java
  src/main/java/seedu/bookmark/storage/JsonAdaptedNote.java
  src/test/data/JsonSerializableLibraryTest/typicalBooksLibrary.json
  src/test/java/seedu/bookmark/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/bookmark/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/bookmark/logic/parser/ParserUtilTest.java
  src/test/java/seedu/bookmark/model/book/NoteTest.java
  src/test/java/seedu/bookmark/storage/JsonAdaptedBookTest.java
  src/test/java/seedu/bookmark/testutil/BookBuilder.java
  src/test/java/seedu/bookmark/testutil/TypicalBooks.java
Labels: type.Task

#111 Add AddCommand and Suggestion feature to DG & Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SuggestionActivityDiagram.puml
  docs/diagrams/SuggestionAlgorithmClassDiagram.puml
  docs/diagrams/SuggestionSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/AlgorithmClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SuggestionActivityDiagram.png
  docs/images/SuggestionAlgorithmClassDiagram.png
  docs/images/SuggestionSequenceDiagram.png
Labels: type.Documentation

#107 Create Word Suggestion for typos
  docs/images/AlgorithmClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/bookmark/MainApp.java
  src/main/java/seedu/bookmark/commons/core/Messages.java
  src/main/java/seedu/bookmark/logic/algorithm/SuggestionAlgorithm.java
  src/main/java/seedu/bookmark/logic/commands/FindCommand.java
  src/main/java/seedu/bookmark/logic/parser/FindCommandParser.java
  src/main/java/seedu/bookmark/model/Model.java
  src/main/java/seedu/bookmark/model/ModelManager.java
  src/main/java/seedu/bookmark/model/WordBank.java
  src/main/java/seedu/bookmark/model/wordstore/Word.java
  src/main/java/seedu/bookmark/model/wordstore/WordComparator.java
  src/main/java/seedu/bookmark/model/wordstore/WordStore.java
  src/main/java/seedu/bookmark/model/wordstore/exceptions/WordNotFoundException.java
  src/main/java/seedu/bookmark/model/wordstore/exceptions/WordStoreNotFoundException.java
  src/test/java/seedu/bookmark/logic/algorithm/SuggestionAlgorithmTest.java
  src/test/java/seedu/bookmark/logic/commands/AddCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/FindCommandTest.java
  src/test/java/seedu/bookmark/logic/parser/CommandParserTest.java
  src/test/java/seedu/bookmark/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/bookmark/model/WordBankTest.java
  src/test/java/seedu/bookmark/model/book/UniqueBookListTest.java
  src/test/java/seedu/bookmark/model/wordstore/WordComparatorTest.java
  src/test/java/seedu/bookmark/model/wordstore/WordStoreTest.java
  src/test/java/seedu/bookmark/model/wordstore/WordTest.java
  src/test/java/seedu/bookmark/testutil/TypicalWords.java
Labels: type.Story

#115 Undo and Redo feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/NewStateActivityDiagram.puml
  docs/diagrams/UndoRedoClassDiagram.puml
  docs/diagrams/UndoRedoStateDiagrams.pptx
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/NewStateActivityDiagram.png
  docs/images/UndoRedoClassDiagram.png
  docs/images/UndoRedoState0.PNG
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.PNG
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.PNG
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.PNG
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.PNG
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.PNG
  docs/images/UndoRedoState5.png
  docs/images/UndoRedoState6.PNG
  docs/images/UndoRedoState7.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/bookmark/logic/commands/CommandResult.java
  src/main/java/seedu/bookmark/logic/commands/EditCommand.java
  src/main/java/seedu/bookmark/logic/commands/ExitCommand.java
  src/main/java/seedu/bookmark/logic/commands/HelpCommand.java
  src/main/java/seedu/bookmark/logic/commands/RedoCommand.java
  src/main/java/seedu/bookmark/logic/commands/UndoCommand.java
  src/main/java/seedu/bookmark/logic/commands/ViewCommand.java
  src/main/java/seedu/bookmark/logic/parser/CommandParser.java
  src/main/java/seedu/bookmark/model/Library.java
  src/main/java/seedu/bookmark/model/Model.java
  src/main/java/seedu/bookmark/model/ModelManager.java
  src/main/java/seedu/bookmark/model/exceptions/RedoException.java
  src/main/java/seedu/bookmark/model/exceptions/UndoException.java
  src/main/java/seedu/bookmark/model/history/HistoryManager.java
  src/main/java/seedu/bookmark/model/history/State.java
  src/main/java/seedu/bookmark/ui/MainWindow.java
  src/test/java/seedu/bookmark/logic/commands/AddCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/CommandResultTest.java
  src/test/java/seedu/bookmark/logic/commands/EditCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/ExitCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/HelpCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/RedoCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/UndoCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/ViewCommandTest.java
  src/test/java/seedu/bookmark/model/ModelManagerTest.java
  src/test/java/seedu/bookmark/model/history/HistoryManagerTest.java
  src/test/java/seedu/bookmark/model/history/StateTest.java
Labels: type.Story

#121 Integrate Notes feature with Ui
  docs/DeveloperGuide.md
  docs/diagrams/UiViewClassDiagram.puml
  docs/diagrams/ViewSwitchingActivityDiagram.puml
  docs/diagrams/ViewSwitchingSequenceDiagram.puml
  docs/images/UiViewClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoRedoState6.png
  docs/images/ViewSwitchingActivityDiagram.png
  docs/images/ViewSwitchingSequenceDiagram.png
  src/main/java/seedu/bookmark/logic/commands/AddNoteCommand.java
  src/main/java/seedu/bookmark/logic/commands/CommandResult.java
  src/main/java/seedu/bookmark/model/book/Book.java
  src/main/java/seedu/bookmark/ui/BookCard.java
  src/main/java/seedu/bookmark/ui/BookListPanel.java
  src/main/java/seedu/bookmark/ui/DetailedBookListPanel.java
  src/main/java/seedu/bookmark/ui/MainWindow.java
  src/main/java/seedu/bookmark/ui/NoteCard.java
  src/main/java/seedu/bookmark/ui/SidebarPanel.java
  src/main/resources/view/BookCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailedBookCard.fxml
  src/main/resources/view/DetailedBookListPanel.fxml
  src/main/resources/view/NoteCard.fxml
  src/test/java/seedu/bookmark/logic/commands/AddNoteCommandTest.java
Labels: type.Story

#122 Minor changes to Word and Wordstore classes
  src/main/java/seedu/bookmark/commons/core/Messages.java
  src/main/java/seedu/bookmark/logic/algorithm/SuggestionAlgorithm.java
  src/main/java/seedu/bookmark/model/WordBank.java
  src/main/java/seedu/bookmark/model/wordstore/Word.java
  src/main/java/seedu/bookmark/model/wordstore/WordStore.java
Labels: type.Task

#128 Edit Help Window
  src/main/java/seedu/bookmark/ui/HelpBox.java
  src/main/java/seedu/bookmark/ui/HelpWindow.java
  src/main/java/seedu/bookmark/ui/help/HelpAction.java
  src/main/java/seedu/bookmark/ui/help/HelpAdd.java
  src/main/java/seedu/bookmark/ui/help/HelpDelete.java
  src/main/java/seedu/bookmark/ui/help/HelpEdit.java
  src/main/java/seedu/bookmark/ui/help/HelpFind.java
  src/main/java/seedu/bookmark/ui/help/HelpGoalAdd.java
  src/main/java/seedu/bookmark/ui/help/HelpGoalDelete.java
  src/main/java/seedu/bookmark/ui/help/HelpList.java
  src/main/java/seedu/bookmark/ui/help/HelpNoteAdd.java
  src/main/java/seedu/bookmark/ui/help/HelpNoteDelete.java
  src/main/java/seedu/bookmark/ui/help/HelpRedo.java
  src/main/java/seedu/bookmark/ui/help/HelpSort.java
  src/main/java/seedu/bookmark/ui/help/HelpUndo.java
  src/main/java/seedu/bookmark/ui/help/HelpView.java
  src/main/resources/images/helpwindowbg.png
  src/main/resources/view/HelpBox.css
  src/main/resources/view/HelpBox.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#129 Updating devguide and userguide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/mainwindow.png
  docs/images/mainwindow_cli.png
  docs/images/mainwindow_list.png
  docs/images/mainwindow_summary.png
Labels: type.Documentation

#135 Ui bug fixes
  src/main/java/seedu/bookmark/logic/commands/EditCommand.java
  src/main/java/seedu/bookmark/logic/commands/GoalCommand.java
  src/main/java/seedu/bookmark/logic/commands/GoalDelCommand.java
  src/main/java/seedu/bookmark/ui/MainWindow.java
  src/test/java/seedu/bookmark/logic/commands/GoalCommandTest.java
  src/test/java/seedu/bookmark/logic/commands/GoalDelCommandTest.java
Labels: type.Bug

#138 Typo fixes
  src/main/java/seedu/bookmark/model/book/Genre.java
  src/main/java/seedu/bookmark/model/book/TotalPages.java
Labels: type.Bug
